export const odishaDistricts = [
  "Angul",
  "Balangir",
  "Baleswar",
  "Bargarh",
  "Bhadrak",
  "Boudh",
  "Cuttack",
  "Deogarh",
  "Dhenkanal",
  "Gajapati",
  "Ganjam",
  "Jagatsinghpur",
  "Jajapur",
  "Jharsuguda",
  "Kalahandi",
  "Kandhamal",
  "Kendrapara",
  "Kendujhar",
  "Khordha",
  "Koraput",
  "Malkangiri",
  "Mayurbhanj",
  "Nabarangpur",
  "Nayagarh",
  "Nuapada",
  "Puri",
  "Rayagada",
  "Sambalpur",
  "Sonepur",
  "Sundargarh",
];


export const odishaBlocks: Record<string, string[]> = {
  Angul: [
    "Angul",
    "Athmallik",
    "Banarpal",
    "Chhendipada",
    "Kaniha",
    "Kishorenagar",
    "Palalahada",
    "Talcher",
  ],

  Balangir: [
    "Agalpur",
    "Balangir",
    "Bangomunda",
    "Belpara",
    "Deogaon",
    "Gudvella",
    "Khaprakhol",
    "Loisinga",
    "Muribahal",
    "Patnagarh",
    "Puintala",
    "Saintala",
    "Titlagarh",
    "Turekela",
  ],

  Baleswar: [
    "Bahanaga",
    "Baleswar",
    "Baliapal",
    "Basta",
    "Bhograi",
    "Jaleswar",
    "Khaira",
    "Nilgiri",
    "Oupada",
    "Remuna",
    "Simulia",
    "Soro",
  ],

  Bargarh: [
    "Ambabhona",
    "Attabira",
    "Bargarh",
    "Barpali",
    "Bhatli",
    "Bheden",
    "Bijepur",
    "Gaisilet",
    "Jharbandh",
    "Padampur",
    "Paikmal",
    "Sohella",
  ],

  Bhadrak: [
    "Basudevpur",
    "Bhadrak",
    "Bhandaripokhari",
    "Bonth",
    "Chandabali",
    "Dhamanagar",
    "Tihidi",
  ],

  Boudh: [
    "Boudh",
    "Harabhanga",
    "Kantamal"
  ],

  Cuttack: [
    "Athagad",
    "Badamba",
    "Banki",
    "Banki-Dampara",
    "Baranga",
    "Cuttacksadar",
    "Kantapada",
    "Mahanga",
    "Narasinghpur",
    "Niali",
    "Nischinta Koili",
    "Salepur",
    "Tangi Choudwar",
    "Tigiria",
  ],

  Deogarh: [
    "Barkote",
    "Reamal",
    "Tileibani"
  ],

  Dhenkanal: [
    "Bhuban",
    "Dhenkanal Sadar",
    "Gondia",
    "Hindol",
    "Kamakhyanagar",
    "Kankada Had",
    "Odapada",
    "Parjang",
  ],

  Gajapati: [
    "Gosani",
    "Gumma",
    "Kasinagar",
    "Mohana",
    "Nuagada",
    "R. Udayagiri",
    "Rayagada",
  ],

  Ganjam: [
    "Aska",
    "Beguniapada",
    "Bellaguntha",
    "Bhanjanagar",
    "Buguda",
    "Chatrapur",
    "Chikiti",
    "Digapahandi",
    "Ganjam",
    "Hinjilicut",
    "Jagannathprasad",
    "Kabisuryanagar",
    "Khallikote",
    "Kukudakhandi",
    "Patrapur",
    "Polosara",
    "Purusottampur",
    "Rangeilunda",
    "Sanakhemundi",
    "Seragarh",
    "Surada",
  ],

  Jagatsinghpur: [
    "Balikuda",
    "Biridi",
    "Erasama",
    "Jagatsinghpur",
    "Kujang",
    "Naugaon",
    "Raghunathpur",
    "Tirtol",
  ],

  Jajapur: [
    "Badachana",
    "Bari",
    "Binjharpur",
    "Danagadi",
    "Dasarathpur",
    "Dharmasala",
    "Jajpur",
    "Korei",
    "Rasulpur",
    "Sukinda",
  ],

  Jharsuguda: [
    "Jharsuguda",
    "Kirmira",
    "Kolabira",
    "Laikera",
    "Lakhanpur"
  ],

  Kalahandi: [
    "Bhawanipatna",
    "Dharamgarh",
    "Golamunda",
    "Jaypatna",
    "Junagarh",
    "Kalampur",
    "Karlamunda",
    "Kesinga",
    "Kokasara",
    "Lanjigarh",
    "Madanpur Rampur",
    "Narla",
    "Thuamul Rampur",
  ],

  Kandhamal: [
    "Baliguda",
    "Chakapada",
    "Daringbadi",
    "G. Udayagiri",
    "K.nuagan",
    "Khajuripada",
    "Kotagarh",
    "Nuagaon",
    "Phiringia",
    "Phulbani",
    "Raikia",
    "Tikabali",
    "Tumudibandh"
  ],

  Kendrapara: [
    "Aul",
    "Derabish",
    "Garadapur",
    "Kendrapara",
    "Mahakalapada",
    "Marsaghai",
    "Pattamundai",
    "Rajkanika",
    "Rajnagar",
  ],

  Kendujhar: [
    "Anandapur",
    "Banspal",
    "Champua",
    "Ghatagaon",
    "Ghasipura",
    "Harichadanpur",
    "Hatadihi",
    "Jhumpura",
    "Joda",
    "Kendujhar Sadar",
    "Patana",
    "Saharpada",
    "Telkoi",
  ],

  Khordha: [
    "Balianta",
    "Balipatna",
    "Banapur",
    "Begunia",
    "Bhubaneswar",
    "Bolgarh",
    "Chilika",
    "Jatni",
    "Khordha",
    "Tangi",
  ],

  Koraput: [
    "Bandhugaon",
    "Boipariguda",
    "Borigumma",
    "Dasmantpur",
    "Jeypore",
    "Koraput",
    "Kotpad",
    "Kundura",
    "Lamtaput",
    "Laxmipur",
    "Narayan patna",
    "Nandapur",
    "Pottangi",
    "Semiliguda",
  ],

  Malkangiri: [
    "Chitrakonda",
    "Kalimela",
    "Khairput",
    "Korukonda",
    "Malkangiri",
    "Mathili",
    "Podia"
  ],

  Mayurbhanj: [
    "Badasahi",
    "Bahalda",
    "Bangriposi",
    "Baripada",
    "Betnoi",
    "Bijalata",
    "Bisoi",
    "Gopabandhu Nagar",
    "Jamda",
    "Joshipur",
    "Karanjia",
    "Kaptipada",
    "Khunta",
    "Kuliana",
    "Kusumi",
    "Morada",
    "Rairangpur",
    "Raruan",
    "Rasgovindpur",
    "Samakhunta",
    "Saraskana",
    "Sukruli",
    "Suliapada",
    "Thakurmunda",
    "Tiring",
    "Udala",
  ],

  Nabarangpur: [
    "Chandahandi",
    "Dabugam",
    "Jharigam",
    "Kosagumuda",
    "Nabarangpur",
    "Nandahandi",
    "Papadahandi",
    "Raighar",
    "Tentulikhunti",
    "Umerkote",
  ],

  Nayagarh: [
    "Bhapur",
    "Dasapalla",
    "Gania",
    "Khandapara",
    "Nuagaon",
    "Nayagarh",
    "Odagaon",
    "Ranpur",
  ],

  Nuapada: [
    "Boden",
    "Khariar",
    "Komna",
    "Nuapada",
    "Sinapali"
  ],

  Puri: [
    "Astaranga",
    "Brahmagiri",
    "Delang",
    "Gop",
    "Kakatpur",
    "Kanas",
    "Krushnaprasad",
    "Nimapada",
    "Pipili",
    "Sadar",
    "Satyabadi",
  ],

  Rayagada: [
    "Bisam Cuttack",
    "Chandrapur",
    "Gudari",
    "Gunupur",
    "Kalyansinghpur",
    "Kasipur",
    "Kolnara",
    "Muniguda",
    "Padmapur",
    "Ramanaguda",
    "Rayagada",
  ],

  Sambalpur: [
    "Bamra",
    "Dhankauda",
    "Jamankira",
    "Jujomura",
    "Kuchinda",
    "Maneswar",
    "Naktideul",
    "Rairakhol",
    "Rengali",
  ],

  Sonepur: [
    "Birmaharajpur",
    "Binika",
    "Dunguripali",
    "Sonepur",
    "Tarabha",
    "Ullunda",
  ],

  Sundargarh: [
    "Balisankara",
    "Bargaon",
    "Bisra",
    "Bonaigarh",
    "Gurundia",
    "Hemgir",
    "Koida",
    "Kuarmunda",
    "Kutra",
    "Lahunipara",
    "Lathikata",
    "Lephripara",
    "Nuagaon",
    "Rajgangpur",
    "Subdega",
    "Sundargarh",
    "Tangarpali",
  ],
};

export const odishaCategory = [
  "Dairy Farmer",
  "Fodder Farmer",
  "Small Animal Farmers",
  "Poultry Farmers",
  "Fishers",
  "Fish Seed Producers",
  "Fish Producers",
  "Brackish Water Fish Farmer",
  "Bio floc Farmer",
  "Marine Fish Farmer"
];