export const odishaDistricts = [
  'Angul',
  'Balangir',
  'Balasore',
  'Bargarh',
  'Bhadrak',
  'Boudh',
  'Cuttack',
  'Deogarh',
  'Dhenkanal',
  'Gajapati',
  'Ganjam',
  'Jagatsinghpur',
  'Jajpur',
  'Jharsuguda',
  'Kalahandi',
  'Kandhamal',
  'Kendrapara',
  'Kendujhar',
  'Khordha',
  'Koraput',
  'Malkangiri',
  'Mayurbhanj',
  'Nabarangpur',
  'Nayagarh',
  'Nuapada',
  'Puri',
  'Rayagada',
  'Sambalpur',
  'Subarnapur',
  'Sundargarh',
];

export const odishaBlocks: Record<string, string[]> = {
  'Angul': ['Angul', 'Athmallik', 'Banarpal', 'Chhendipada', 'Kaniha', 'Kishorenagar', 'Pallahara', 'Talcher'],
  'Balangir': ['Agalpur', 'Balangir', 'Bangomunda', 'Belpara', 'Deogaon', 'Gudvela', 'Kantabanji', 'Loisingha', 'Muribahal', 'Patnagarh', 'Puintala', 'Saintala', 'Titlagarh', 'Turekela'],
  'Balasore': ['Balasore', 'Baliapal', 'Basta', 'Bhogarai', 'Jaleswar', 'Khaira', 'Nilagiri', 'Remuna', 'Simulia', 'Soro'],
  'Bargarh': ['Ambabhona', 'Attabira', 'Bargarh', 'Barpali', 'Bhatli', 'Bheden', 'Bijepur', 'Gaisilet', 'Jharbandh', 'Padampur', 'Paikmal', 'Sohela'],
  'Bhadrak': ['Basudevpur', 'Bhadrak', 'Bonth', 'Chandabali', 'Dhamnagar', 'Tihidi', 'Bhandaripokhari'],
  'Boudh': ['Boudh', 'Kantamal', 'Harbhanga', 'Purunakatak'],
  'Cuttack': ['Athagad', 'Badamba', 'Banki', 'Baramba', 'Cuttack Sadar', 'Dampara', 'Kantapada', 'Mahanga', 'Narasinghpur', 'Niali', 'Salepur', 'Tangi-Choudwar', 'Tigiria'],
  'Deogarh': ['Bamra', 'Barkote', 'Deogarh', 'Reamal', 'Tileibani'],
  'Dhenkanal': ['Bhuban', 'Dhenkanal Sadar', 'Gandia', 'Gondia', 'Hindol', 'Kamakshyanagar', 'Kankadahad', 'Odapada', 'Parjang'],
  'Gajapati': ['Chandragiri', 'Gumma', 'Kasinagar', 'Mohana', 'Nuagada', 'Paralakhemundi', 'Rayagada', 'R.Udayagiri'],
  'Ganjam': ['Aska', 'Bellaguntha', 'Berhampur', 'Bhanjanagar', 'Buguda', 'Chhatrapur', 'Chikiti', 'Digapahandi', 'Ganjam', 'Hinjilicut', 'Jarada', 'Kabisuryanagar', 'Khallikote', 'Kukudakhandi', 'Patrapur', 'Polsara', 'Purusottampur', 'Rangeilunda', 'Sanakhemundi', 'Seragarh', 'Sorada', 'Surada'],
  'Jagatsinghpur': ['Balikuda', 'Biridi', 'Erasama', 'Jagatsinghpur', 'Kujang', 'Naugaon', 'Raghunathpur', 'Tirtol'],
  'Jajpur': ['Bari', 'Binjharpur', 'Dasarathpur', 'Dharmasala', 'Jajpur', 'Korei', 'Rasulpur', 'Sukinda'],
  'Jharsuguda': ['Jharsuguda', 'Kirmira', 'Kolabira', 'Laikera', 'Lakhanpur'],
  'Kalahandi': ['Bhawanipatna', 'Dharamgarh', 'Golamunda', 'Jayapatna', 'Jaipatna', 'Junagarh', 'Karlamunda', 'Kashipur', 'Kesinga', 'Kokasara', 'Lanjigarh', 'M. Rampur', 'Narla', 'Thuamul Rampur'],
  'Kandhamal': ['Balliguda', 'Baliguda', 'Chakapada', 'Daringbadi', 'G. Udayagiri', 'Khajuripada', 'Kotagarh', 'Nuagaon', 'Phiringia', 'Phulbani', 'Raikia', 'Tikabali'],
  'Kendrapara': ['Aul', 'Derabish', 'Garadpur', 'Kendrapara', 'Mahakalapada', 'Marsaghai', 'Pattamundai', 'Rajkanika', 'Rajnagar'],
  'Kendujhar': ['Anandapur', 'Banspal', 'Champua', 'Ghatagaon', 'Hatadihi', 'Jhumpura', 'Kendujhar', 'Patna', 'Saharpada', 'Telkoi'],
  'Khordha': ['Balianta', 'Balipatna', 'Banapur', 'Begunia', 'Bhubaneswar', 'Bolgarh', 'Chilika', 'Jatani', 'Khordha', 'Tangi'],
  'Koraput': ['Bandhugaon', 'Boipariguda', 'Dasmantpur', 'Jeypore', 'Koraput', 'Kotpad', 'Kundra', 'Lamataput', 'Laxmipur', 'Narayanpatna', 'Nandapur', 'Pottangi', 'Semiliguda'],
  'Malkangiri': ['Chitrakonda', 'Kalimela', 'Khairput', 'Korukonda', 'Kudumulugumma', 'Malkangiri', 'Mathili'],
  'Mayurbhanj': ['Badasahi', 'Bangiriposi', 'Baripada', 'Bisoi', 'Gopabandhu Nagar', 'Jamda', 'Karanjia', 'Kaptipada', 'Khunta', 'Kuliana', 'Kusumi', 'Morada', 'Rairangpur', 'Raruan', 'Rasgovindpur', 'Samakhunta', 'Saraskana', 'Suliapada', 'Thakurmunda', 'Tiring', 'Udala'],
  'Nabarangpur': ['Chandahandi', 'Dabugaon', 'Jharigam', 'Kosagumuda', 'Nabarangpur', 'Nandahandi', 'Papadahandi', 'Raighar', 'Tentulikhunti', 'Umerkote'],
  'Nayagarh': ['Banpur', 'Bhapur', 'Dasapalla', 'Gania', 'Khandapada', 'Nuagaon', 'Nayagarh', 'Odagaon', 'Ranpur'],
  'Nuapada': ['Boden', 'Khariar', 'Komna', 'Nuapada', 'Sinapali'],
  'Puri': ['Astaranga', 'Brahmagiri', 'Delang', 'Gop', 'Kakatpur', 'Kanas', 'Krushnaprasad', 'Nimapara', 'Puri', 'Satyabadi'],
  'Rayagada': ['Bisam Cuttack', 'Chandrapur', 'Gunupur', 'Kalyansinghpur', 'Kasipur', 'Kolnara', 'Muniguda', 'Padmapur', 'Ramanaguda', 'Rayagada'],
  'Sambalpur': ['Bamra', 'Dhankauda', 'Jujumura', 'Kuchinda', 'Maneswar', 'Naktideul', 'Rairakhol', 'Rengali', 'Sambalpur', 'Jamankira'],
  'Subarnapur': ['Birmaharajpur', 'Binka', 'Dunguripali', 'Subarnapur', 'Tarabha', 'Ulunda'],
  'Sundargarh': ['Balisankara', 'Bargaon', 'Bisra', 'Bonai', 'Gurundia', 'Hemgir', 'Koida', 'Kuarmunda', 'Kutra', 'Lahunipara', 'Lathikata', 'Lephripara', 'Nuagaon', 'Rajgangpur', 'Subdega', 'Sundargarh', 'Tangarpali'],
};

export const odishaDepartments = [
  'Agriculture & Farmers Empowerment',
  'Animal Husbandry & Veterinary Services',
  'Beverages Control',
  'Panchayati Raj & Drinking Water',
  'Rural Development',
  'Child Rights',
  'Cooperation',
  'Culture',
  'Electronics & IT',
  'Energy',
  'Finance',
  'Fisheries & Animal Resources Development',
  'Food Supplies & Consumer Welfare',
  'Forest & Environment',
  'GA & PG Department',
  'Health & Family Welfare',
  'Higher Education',
  'Housing & Urban Development',
  'Industries',
  'Information & Public Relations',
  'Labour & ESI',
  'Law',
  'MSME',
  'Mission Shakti',
  'Odia Language, Literature & Culture',
  'Parliamentary Affairs',
  'Planning & Convergence',
  'Public Enterprises',
  'Revenue & Disaster Management',
  'School & Mass Education',
  'Science & Technology',
  'Skill Development & Technical Education',
  'Social Security & Empowerment of Persons with Disabilities',
  'Sports & Youth Services',
  'Steel & Mines',
  'ST & SC Development',
  'Tourism',
  'Transport',
  'Water Resources',
  'Women & Child Development',
  'Other',
];